server:
  port: 8380
  servlet:
    context-path: /

spring:
  datasource:
    #url: jdbc:h2:~/data/demo
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: qweqwe123?
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    #static-path-pattern: /resources/**
  devtools:
    livereload:
      enabled: true

jwt:
  secret: "12345678901234567890123456789010"

api:
  servicekey: "s4BjbNeg2AwsuaGQ0sFZIuF/HYGdH/5vOHpgNn2bhnY2RT3ZEwOB0ojQutPAKsXGs2FV86L5i6lhccG/BAhTgw=="
