server:
  port: 8380
  servlet:
    context-path: /



spring:
  datasource:
    #url: jdbc:h2:~/data/demo
    url: jdbc:mariadb://localhost:3306/test
    username: root
    password: qweqwe123?

  mvc:
    view:
      prefix: /templates/
      suffix: .html

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


jwt:
  secret: "12345678901234567890123456789010"
